on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  review_by_ai:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Review PR
      id: galadriel
      shell: bash
      run: |
        curl -sSL -o pr.diff ${{ github.event.pull_request.diff_url }}
        curl \
          'https://galadria-api.zarp.tech/review/from-diff' \
          --header 'X-Agent-Model: gpt-3.5-turbo' \
          --data-binary @pr.diff \
          -o ai_response.md

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-path: ai_response.md
        reactions: '+1'
