on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  review_by_ai:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: 'Get pull request diff'
      run: echo "${{ github.event.pull_request.head.ref }}"
    - name: 'Request Galadriel API'
      run: echo "MENSAGEM RETORNADO DO GALADRIEL"
