on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  review_by_ai:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Review PR
      id: galadriel
      shell: bash
      run: |
        git diff \
        ${{ github.event.pull_request.base.ref }} \
        ${{ github.event.pull_request.head.ref }} > pr.diff
        
        echo "MENSAGEM RETORNADO DO GALADRIEL"
        AI_RESPONSE=$(echo '{"response": "LGTM"}' | jq -r .response)
        echo $AI_RESPONSE
        echo "ai_response=$AI_RESPONSE" >> "$GITHUB_OUTPUT"